language: python
cache: pip
python:
  - 3.6

before_install:
  - pip install --upgrade setuptools
  - pip uninstall -y six
  - sync && echo 3 | sudo tee /proc/sys/vm/drop_caches  # https://github.com/elastic/elasticsearch/issues/28650

install:
  - pip install --upgrade -e .
  - pip install crash mypy

script:
  - tests/client_tests/go/run.sh
  - find tests -name "*.py" | xargs mypy --ignore-missing-imports
  - find src -name "*.py" | xargs mypy --ignore-missing-imports
  - cd tests && python -m unittest -vvv $(find . -name "test_*.py" | grep -v test_upgrade.py | xargs readlink -f)

env:
  - DEBUG=false

notifications:
  email: false

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-set-default
      - dh-golang
