language: python
cache: pip
python:
    - 3.6

before_install:
    - pip install --upgrade setuptools
    - pip uninstall -y six

install:
    - pip install --upgrade --process-dependency-links -e .
    - pip install crash

script:
    - tests/client_tests/go/run.sh
    - cd tests && python -m unittest -vf

env:
  - DEBUG=true

notifications:
    email: false

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-set-default
      - dh-golang
