language: python
cache: pip
python:
    - 3.6

before_install:
    - pip install --upgrade setuptools
    - pip uninstall -y six
    - sync && echo 3 | sudo tee /proc/sys/vm/drop_caches # https://github.com/elastic/elasticsearch/issues/28650

install:
    - pip install --upgrade --process-dependency-links -e .
    - pip install crash

script:
    - tests/client_tests/go/run.sh
    - cd tests && python -m unittest -vvv $(find . -name "test_*.py" | grep -v test_upgrade.py | xargs readlink -f)

env:
  - DEBUG=false

notifications:
    email: false

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-set-default
      - dh-golang
