language: python
cache:
  directories:
    - $HOME/.stack

python:
  - 3.6

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - pip install --upgrade setuptools
  - pip uninstall -y six
  - sync && echo 3 | sudo tee /proc/sys/vm/drop_caches  # https://github.com/elastic/elasticsearch/issues/28650

install:
  - pip install --upgrade -e .
  - pip install crash mypy flake8

script:
  - tests/client_tests/go/run.sh
  - tests/client_tests/php/run.sh
  - tests/client_tests/haskell/run.sh
  - find tests -name "*.py" | xargs mypy --ignore-missing-imports
  - find src -name "*.py" | xargs mypy --ignore-missing-imports
  - flake8 src/ tests/
  - cd tests && python -m unittest -vvv $(find . -name "test_*.py" | grep -v test_upgrade.py | xargs readlink -f)

env:
  - DEBUG=false

notifications:
  email: false

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-set-default
      - dh-golang
